namespace TCG
{
	public enum HoloRarity
	{
		// os
		OS_STAR_HOLO,
		OS_COSMOS_HOLO,

		OS_COSMOS_HOLO_ENERGY,

		OS_REVERSE_COSMOS_HOLO,

		// neo
		NEO_COSMOS_HOLO,

		NEO_REVERSE_COSMOS_HOLO,

		// legendary collection
		LC_STAR_HOLO,

		LC_REVERSE_SILVER_FIREWORKS_HOLO,

		// e series
		E_COSMOS_HOLO,

		E_REVERSE_REFRACTOR_HOLO,

		// ex
		EX_COSMOS_HOLO,
		EX_COSMOS_HOLO_VICTORY_MEDAL,
		EX_COSMOS_HOLO_DELTA,
		EX_VERTICAL_REFRACTOR_HOLO_DELTA,

		EX_PIXEL_WAVE_HOLO_ENERGY,

		EX_REVERSE_REFRACTOR_HOLO,
		EX_BIG_ENERGY_HOLO_HL,
		EX_ENERGY_HOLO_FL,
		EX_ENERGY_HOLO_TRR,
		EX_PRISM_HOLO_D,
		EX_2D_POKEBALL_HOLO_E,
		EX_3D_POKEBALL_HOLO_UF,
		EX_REFRACTOR_HOLO_DS,
		EX_COSMOS_HOLO_LM,
		EX_REFRACTOR_HOLO_HP,
		EX_REFRACTOR_HOLO_CG,
		EX_REFRACTOR_HOLO_DF,
		EX_REFRACTOR_HOLO_PK,

		// DP
		DP_COSMOS_HOLO,
		DP_COSMOS_HOLO_VICTORY_MEDAL,
		DP_CRACKED_ICE_HOLO,

		DP_MIRROR_HOLO_ENERGY,
		DP_SCRATCH_HOLO_ENERGY,

		DP_REVERSE_MIRROR_HOLO,

		DP_REVERSE_CRACKED_ICE_HOLO,
		DP_REVERSE_SCRATCH_HOLO,
		DP_REVERSE_REFRACTOR_HOLO,

		DP_RUMBLE_COSMOS_HOLO_LOGO,

		// HGSS
		HGSS_COSMOS_HOLO,
		HGSS_COSMOS_HOLO_VICTORY_MEDAL,
		HGSS_CRACKED_ICE_HOLO,

		HGSS_MIRROR_HOLO_ENERGY_COL,
		HGSS_SCRATCH_HOLO_ENERGY,
		HGSS_SCRATCH_HOLO_ENERGY_COL,

		HGSS_REVERSE_MIRROR_HOLO,

		HGSS_REVERSE_SCRATCH_HOLO,

		// BW & XY
		BWXY_TINSEL_HOLO,
		BWXY_TINSEL_HOLO_PLASMA,
		BWXY_SHEEN_HOLO,
		BWXY_COSMOS_HOLO,
		BWXY_COSMOS_HOLO_PLASMA,
		BWXY_MIRROR_HOLO,
		BWXY_CRACKED_ICE_HOLO,
		BWXY_CRACKED_ICE_HOLO_PLASMA,
		BWXY_CONFETTI_HOLO,

		BWXY_SCRATCH_HOLO_ENERGY_BW,
		BWXY_MIRROR_HOLO_ENERGY,
		BWXY_SCRATCH_HOLO_ENERGY,
		BWXY_SHEEN_HOLO_ENERGY,

		BWXY_REVERSE_MIRROR_HOLO,
		BWXY_REVERSE_MIRROR_HOLO_PLASMA,
		BWXY_REVERSE_ENERGY_HOLO,

		BWXY_REVERSE_SCRATCH_HOLO,
		BWXY_REVERSE_SCRATCH_HOLO_PLASMA,

		// SM


		// SWSH


		// SV

	}
}