using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TCG
{
	public static class PrizePacks
	{
		private static PrizePack[] ThePrizePacks =
		{
			new PrizePack(1,
				HoloCards.Find(Sets.Darkness_Ablaze, 150, HoloRarity.SWSH_LINE_HOLO),
				HoloCards.Find(Sets.Sword_Shield, 147, HoloRarity.SWSH_LINE_HOLO),
				HoloCards.Find(Sets.Darkness_Ablaze, 78, HoloRarity.SWSH_LINE_HOLO),
				HoloCards.Find(Sets.Sword_Shield, 56, HoloRarity.SWSH_LINE_HOLO),
				HoloCards.Find(Sets.Rebel_Clash, 109, HoloRarity.SWSH_LINE_HOLO),
				HoloCards.Find(Sets.Evolving_Skies, 55, HoloRarity.SWSH_LINE_HOLO),
				HoloCards.Find(Sets.Darkness_Ablaze, 36, HoloRarity.SWSH_LINE_HOLO),
				HoloCards.Find(Sets.Sword_Shield, 117, HoloRarity.SWSH_LINE_HOLO),
				HoloCards.Find(Sets.Chilling_Reign, 43, HoloRarity.SWSH_LINE_HOLO),
				HoloCards.Find(Sets.Sword_Shield, 58, HoloRarity.SWSH_LINE_HOLO),
				HoloCards.Find(Sets.Chilling_Reign, 70, HoloRarity.SWSH_LINE_HOLO),
				HoloCards.Find(Sets.Chilling_Reign, 88, HoloRarity.SWSH_LINE_HOLO),
				HoloCards.Find(Sets.Darkness_Ablaze, 83, HoloRarity.SWSH_LINE_HOLO),
				HoloCards.Find(Sets.Evolving_Skies, 76, HoloRarity.SWSH_LINE_HOLO),
				HoloCards.Find(Sets.Vivid_Voltage, 131, HoloRarity.SWSH_LINE_HOLO),
				HoloCards.Find(Sets.Chilling_Reign, 103, HoloRarity.SWSH_LINE_HOLO),
				HoloCards.Find(Sets.Sword_Shield, 156, HoloRarity.SWSH_LINE_HOLO),
				HoloCards.Find(Sets.Darkness_Ablaze, 159, HoloRarity.SWSH_LINE_HOLO),
				HoloCards.Find(Sets.Shining_Fates, 58, HoloRarity.SWSH_LINE_HOLO),
				HoloCards.Find(Sets.Darkness_Ablaze, 160, HoloRarity.SWSH_LINE_HOLO),
				HoloCards.Find(Sets.Battle_Styles, 123, HoloRarity.SWSH_LINE_HOLO),
				HoloCards.Find(Sets.Evolving_Skies, 143, HoloRarity.SWSH_LINE_HOLO),
				HoloCards.Find(Sets.Sword_Shield, 159, HoloRarity.SWSH_LINE_HOLO),
				HoloCards.Find(Sets.Battle_Styles, 125, HoloRarity.SWSH_LINE_HOLO),
				HoloCards.Find(Sets.Chilling_Reign, 140, HoloRarity.SWSH_LINE_HOLO),
				HoloCards.Find(Sets.Battle_Styles, 129, HoloRarity.SWSH_LINE_HOLO),
				HoloCards.Find(Sets.Sword_Shield, 169, HoloRarity.SWSH_LINE_HOLO),
				HoloCards.Find(Sets.Sword_Shield, 170, HoloRarity.SWSH_LINE_HOLO),
				HoloCards.Find(Sets.Vivid_Voltage, 157, HoloRarity.SWSH_LINE_HOLO),
				HoloCards.Find(Sets.Sword_Shield, 171, HoloRarity.SWSH_LINE_HOLO),
				HoloCards.Find(Sets.Chilling_Reign, 148, HoloRarity.SWSH_LINE_HOLO),
				HoloCards.Find(Sets.Shining_Fates, 60, HoloRarity.SWSH_LINE_HOLO),
				HoloCards.Find(Sets.Sword_Shield, 179, HoloRarity.SWSH_LINE_HOLO),
				HoloCards.Find(Sets.Evolving_Skies, 152, HoloRarity.SWSH_LINE_HOLO),
				HoloCards.Find(Sets.Sword_Shield, 180, HoloRarity.SWSH_LINE_HOLO),
				HoloCards.Find(Sets.Rebel_Clash, 165, HoloRarity.SWSH_LINE_HOLO),
				HoloCards.Find(Sets.Evolving_Skies, 161, HoloRarity.SWSH_LINE_HOLO),
				HoloCards.Find(Sets.Sword_Shield, 183, HoloRarity.SWSH_LINE_HOLO),
				HoloCards.Find(Sets.Darkness_Ablaze, 172, HoloRarity.SWSH_LINE_HOLO),
				HoloCards.Find(Sets.Sword_Shield, 186, HoloRarity.SWSH_REVERSE_LINE_HOLO),
				HoloCards.Find(Sets.Rebel_Clash, 171, HoloRarity.SWSH_REVERSE_LINE_HOLO),
				HoloCards.Find(Sets.Battle_Styles, 140, HoloRarity.SWSH_REVERSE_LINE_HOLO),
				HoloCards.Find(Sets.Battle_Styles, 141, HoloRarity.SWSH_REVERSE_LINE_HOLO),
				HoloCards.FindUnnumbered("Basic Grass Energy", HoloRarity.SWSH_LINE_HOLO_ENERGY),
				HoloCards.FindUnnumbered("Basic Fire Energy", HoloRarity.SWSH_LINE_HOLO_ENERGY),
				HoloCards.FindUnnumbered("Basic Water Energy", HoloRarity.SWSH_LINE_HOLO_ENERGY),
				HoloCards.FindUnnumbered("Basic Lightning Energy", HoloRarity.SWSH_LINE_HOLO_ENERGY),
				HoloCards.FindUnnumbered("Basic Psychic Energy", HoloRarity.SWSH_LINE_HOLO_ENERGY),
				HoloCards.FindUnnumbered("Basic Fighting Energy", HoloRarity.SWSH_LINE_HOLO_ENERGY),
				HoloCards.FindUnnumbered("Basic Darkness Energy", HoloRarity.SWSH_LINE_HOLO_ENERGY),
				HoloCards.FindUnnumbered("Basic Metal Energy", HoloRarity.SWSH_LINE_HOLO_ENERGY)
			),
			new PrizePack(2,
				HoloCards.Find(Sets.Brilliant_Stars, 121, HoloRarity.SWSH_LINE_HOLO),
				HoloCards.Find(Sets.Evolving_Skies, 55, HoloRarity.SWSH_LINE_HOLO),
				HoloCards.Find(Sets.Battle_Styles, 96, HoloRarity.SWSH_LINE_HOLO),
				HoloCards.Find(Sets.Chilling_Reign, 43, HoloRarity.SWSH_LINE_HOLO),
				HoloCards.Find(Sets.Chilling_Reign, 70, HoloRarity.SWSH_LINE_HOLO),
				HoloCards.Find(Sets.Brilliant_Stars, 41, HoloRarity.SWSH_LINE_HOLO),
				HoloCards.Find(Sets.Fusion_Strike, 124, HoloRarity.SWSH_LINE_HOLO),
				HoloCards.Find(Sets.Battle_Styles, 37, HoloRarity.SWSH_LINE_HOLO),
				HoloCards.Find(Sets.Chilling_Reign, 88, HoloRarity.SWSH_LINE_HOLO),
				HoloCards.Find(Sets.Brilliant_Stars, 8, HoloRarity.SWSH_LINE_HOLO),
				HoloCards.Find(Sets.Fusion_Strike, 225, HoloRarity.SWSH_LINE_HOLO),
				HoloCards.Find(Sets.Brilliant_Stars, 132, HoloRarity.SWSH_LINE_HOLO),
				HoloCards.Find(Sets.Battle_Styles, 123, HoloRarity.SWSH_LINE_HOLO),
				HoloCards.Find(Sets.Brilliant_Stars, 135, HoloRarity.SWSH_LINE_HOLO),
				HoloCards.Find(Sets.Evolving_Skies, 143, HoloRarity.SWSH_LINE_HOLO),
				HoloCards.Find(Sets.Fusion_Strike, 229, HoloRarity.SWSH_LINE_HOLO),
				HoloCards.Find(Sets.Sword_Shield, 159, HoloRarity.SWSH_LINE_HOLO),
				HoloCards.Find(Sets.Fusion_Strike, 233, HoloRarity.SWSH_LINE_HOLO),
				HoloCards.Find(Sets.Battle_Styles, 125, HoloRarity.SWSH_LINE_HOLO),
				HoloCards.Find(Sets.Chilling_Reign, 140, HoloRarity.SWSH_LINE_HOLO),
				HoloCards.Find(Sets.Brilliant_Stars, 141, HoloRarity.SWSH_LINE_HOLO),
				HoloCards.Find(Sets.Battle_Styles, 129, HoloRarity.SWSH_LINE_HOLO),
				HoloCards.Find(Sets.Brilliant_Stars, 144, HoloRarity.SWSH_LINE_HOLO),
				HoloCards.Find(Sets.Chilling_Reign, 148, HoloRarity.SWSH_LINE_HOLO),
				HoloCards.Find(Sets.Fusion_Strike, 236, HoloRarity.SWSH_LINE_HOLO),
				HoloCards.Find(Sets.Brilliant_Stars, 147, HoloRarity.SWSH_LINE_HOLO),
				HoloCards.Find(Sets.Evolving_Skies, 152, HoloRarity.SWSH_LINE_HOLO),
				HoloCards.Find(Sets.Sword_Shield, 180, HoloRarity.SWSH_LINE_HOLO),
				HoloCards.Find(Sets.Evolving_Skies, 161, HoloRarity.SWSH_LINE_HOLO),
				HoloCards.Find(Sets.Sword_Shield, 183, HoloRarity.SWSH_LINE_HOLO),
				HoloCards.Find(Sets.Brilliant_Stars, 150, HoloRarity.SWSH_LINE_HOLO),
				HoloCards.Find(Sets.Brilliant_Stars, 151, HoloRarity.SWSH_REVERSE_LINE_HOLO),
				HoloCards.Find(Sets.Fusion_Strike, 244, HoloRarity.SWSH_REVERSE_LINE_HOLO),
				HoloCards.Find(Sets.Battle_Styles, 140, HoloRarity.SWSH_REVERSE_LINE_HOLO),
				HoloCards.Find(Sets.Battle_Styles, 141, HoloRarity.SWSH_REVERSE_LINE_HOLO),
				HoloCards.FindUnnumbered("Basic Grass Energy", HoloRarity.SWSH_LINE_HOLO_ENERGY_STAR),
				HoloCards.FindUnnumbered("Basic Fire Energy", HoloRarity.SWSH_LINE_HOLO_ENERGY_STAR),
				HoloCards.FindUnnumbered("Basic Water Energy", HoloRarity.SWSH_LINE_HOLO_ENERGY_STAR),
				HoloCards.FindUnnumbered("Basic Lightning Energy", HoloRarity.SWSH_LINE_HOLO_ENERGY_STAR),
				HoloCards.FindUnnumbered("Basic Psychic Energy", HoloRarity.SWSH_LINE_HOLO_ENERGY_STAR),
				HoloCards.FindUnnumbered("Basic Fighting Energy", HoloRarity.SWSH_LINE_HOLO_ENERGY_STAR),
				HoloCards.FindUnnumbered("Basic Darkness Energy", HoloRarity.SWSH_LINE_HOLO_ENERGY_STAR),
				HoloCards.FindUnnumbered("Basic Metal Energy", HoloRarity.SWSH_LINE_HOLO_ENERGY_STAR)
			),
			new PrizePack(3,
				HoloCards.Find(Sets.Lost_Origin, 73, HoloRarity.SWSH_PIXEL_COSMOS_HOLO_LOST),
				HoloCards.Find(Sets.Brilliant_Stars, 121, HoloRarity.SWSH_PIXEL_COSMOS_HOLO),
				HoloCards.Find(Sets.Lost_Origin, 50, HoloRarity.SWSH_PIXEL_COSMOS_HOLO_LOST),
				HoloCards.Find(Sets.Scarlet_Violet, 61, HoloRarity.SV_PIXEL_COSMOS_HOLO),
				HoloCards.Find(Sets.Brilliant_Stars, 7, HoloRarity.SWSH_PIXEL_COSMOS_HOLO),
				HoloCards.Find(Sets.Astral_Radiance, 43, HoloRarity.SWSH_PIXEL_COSMOS_HOLO),
				HoloCards.Find(Sets.Silver_Tempest, 68, HoloRarity.SWSH_PIXEL_COSMOS_HOLO),
				HoloCards.Find(Sets.Brilliant_Stars, 41, HoloRarity.SWSH_PIXEL_COSMOS_HOLO),
				HoloCards.Find(Sets.Lost_Origin, 70, HoloRarity.SWSH_PIXEL_COSMOS_HOLO_LOST),
				HoloCards.Find(Sets.Scarlet_Violet, 62, HoloRarity.SV_PIXEL_COSMOS_HOLO),
				HoloCards.Find(Sets.Silver_Tempest, 38, HoloRarity.SWSH_PIXEL_COSMOS_HOLO),
				HoloCards.Find(Sets.Scarlet_Violet, 166, HoloRarity.SV_PIXEL_COSMOS_HOLO),
				HoloCards.Find(Sets.Scarlet_Violet, 167, HoloRarity.SV_PIXEL_COSMOS_HOLO),
				HoloCards.Find(Sets.Brilliant_Stars, 132, HoloRarity.SWSH_PIXEL_COSMOS_HOLO),
				HoloCards.Find(Sets.Astral_Radiance, 136, HoloRarity.SWSH_PIXEL_COSMOS_HOLO),
				HoloCards.Find(Sets.Lost_Origin, 156, HoloRarity.SWSH_PIXEL_COSMOS_HOLO),
				HoloCards.Find(Sets.Scarlet_Violet, 170, HoloRarity.SV_PIXEL_COSMOS_HOLO),
				HoloCards.Find(Sets.Astral_Radiance, 141, HoloRarity.SWSH_PIXEL_COSMOS_HOLO),
				HoloCards.Find(Sets.Astral_Radiance, 145, HoloRarity.SWSH_PIXEL_COSMOS_HOLO),
				HoloCards.Find(Sets.Astral_Radiance, 146, HoloRarity.SWSH_PIXEL_COSMOS_HOLO),
				HoloCards.Find(Sets.Scarlet_Violet, 175, HoloRarity.SV_PIXEL_COSMOS_HOLO),
				HoloCards.Find(Sets.Crown_Zenith, 135, HoloRarity.SWSH_PIXEL_COSMOS_HOLO_LOST),
				HoloCards.Find(Sets.Brilliant_Stars, 144, HoloRarity.SWSH_PIXEL_COSMOS_HOLO),
				HoloCards.Find(Sets.Lost_Origin, 163, HoloRarity.SWSH_PIXEL_COSMOS_HOLO_LOST),
				HoloCards.Find(Sets.Scarlet_Violet, 181, HoloRarity.SV_PIXEL_COSMOS_HOLO),
				HoloCards.Find(Sets.Brilliant_Stars, 146, HoloRarity.SWSH_PIXEL_COSMOS_HOLO),
				HoloCards.Find(Sets.Scarlet_Violet, 189, HoloRarity.SV_PIXEL_COSMOS_HOLO),
				HoloCards.Find(Sets.Scarlet_Violet, 190, HoloRarity.SV_PIXEL_COSMOS_HOLO),
				HoloCards.Find(Sets.Scarlet_Violet, 191, HoloRarity.SV_PIXEL_COSMOS_HOLO),
				HoloCards.Find(Sets.Scarlet_Violet, 194, HoloRarity.SV_PIXEL_COSMOS_HOLO),
				HoloCards.Find(Sets.Astral_Radiance, 154, HoloRarity.SWSH_PIXEL_COSMOS_HOLO),
				HoloCards.Find(Sets.Crown_Zenith, 145, HoloRarity.SWSH_PIXEL_COSMOS_HOLO),
				HoloCards.Find(Sets.Crown_Zenith, 146, HoloRarity.SWSH_PIXEL_COSMOS_HOLO),
				HoloCards.Find(Sets.Scarlet_Violet, 196, HoloRarity.SV_PIXEL_COSMOS_HOLO),
				HoloCards.Find(Sets.Brilliant_Stars, 151, HoloRarity.SWSH_REVERSE_PIXEL_COSMOS_HOLO),
				HoloCards.FindUnnumbered("Basic Grass Energy", HoloRarity.SWSH_PIXEL_COSMOS_HOLO_ENERGY_STAR),
				HoloCards.FindUnnumbered("Basic Fire Energy", HoloRarity.SWSH_PIXEL_COSMOS_HOLO_ENERGY_STAR),
				HoloCards.FindUnnumbered("Basic Water Energy", HoloRarity.SWSH_PIXEL_COSMOS_HOLO_ENERGY_STAR),
				HoloCards.FindUnnumbered("Basic Lightning Energy", HoloRarity.SWSH_PIXEL_COSMOS_HOLO_ENERGY_STAR),
				HoloCards.FindUnnumbered("Basic Psychic Energy", HoloRarity.SWSH_PIXEL_COSMOS_HOLO_ENERGY_STAR),
				HoloCards.FindUnnumbered("Basic Fighting Energy", HoloRarity.SWSH_PIXEL_COSMOS_HOLO_ENERGY_STAR),
				HoloCards.FindUnnumbered("Basic Darkness Energy", HoloRarity.SWSH_PIXEL_COSMOS_HOLO_ENERGY_STAR),
				HoloCards.FindUnnumbered("Basic Metal Energy", HoloRarity.SWSH_PIXEL_COSMOS_HOLO_ENERGY_STAR)
			),
			new PrizePack(4,
				HoloCards.Find(Sets.Scarlet_Violet, 89, HoloRarity.SV_PIXEL_COSMOS_HOLO),
				HoloCards.Find(Sets.Silver_Tempest, 68, HoloRarity.SWSH_PIXEL_COSMOS_HOLO),
				HoloCards.Find(Sets.Scarlet_Violet, 96, HoloRarity.SV_PIXEL_COSMOS_HOLO),
				HoloCards.Find(Sets.Crown_Zenith, 36, HoloRarity.SWSH_PIXEL_COSMOS_HOLO),
				HoloCards.Find(Sets.Paldea_Evolved, 89, HoloRarity.SV_PIXEL_COSMOS_HOLO),
				HoloCards.Find(Sets.Silver_Tempest, 38, HoloRarity.SWSH_PIXEL_COSMOS_HOLO),
				HoloCards.Find(Sets.Paldea_Evolved, 171, HoloRarity.SV_PIXEL_COSMOS_HOLO),
				HoloCards.Find(Sets.Scarlet_Violet, 166, HoloRarity.SV_PIXEL_COSMOS_HOLO),
				HoloCards.Find(Sets.Scarlet_Violet, 167, HoloRarity.SV_PIXEL_COSMOS_HOLO),
				HoloCards.Find(Sets.Paldea_Evolved, 172, HoloRarity.SV_PIXEL_COSMOS_HOLO),
				HoloCards.Find(Sets.Paldea_Evolved, 173, HoloRarity.SV_PIXEL_COSMOS_HOLO),
				HoloCards.Find(Sets.Silver_Tempest, 153, HoloRarity.SWSH_PIXEL_COSMOS_HOLO),
				HoloCards.Find(Sets.Paldea_Evolved, 177, HoloRarity.SV_PIXEL_COSMOS_HOLO),
				HoloCards.Find(Sets.Scarlet_Violet, 170, HoloRarity.SV_PIXEL_COSMOS_HOLO),
				HoloCards.Find(Sets.Paldea_Evolved, 185, HoloRarity.SV_PIXEL_COSMOS_HOLO),
				HoloCards.Find(Sets.Scarlet_Violet, 175, HoloRarity.SV_PIXEL_COSMOS_HOLO),
				HoloCards.Find(Sets.Scarlet_Violet, 176, HoloRarity.SV_PIXEL_COSMOS_HOLO),
				HoloCards.Find(Sets.Lost_Origin, 161, HoloRarity.SWSH_PIXEL_COSMOS_HOLO_LOST),
				HoloCards.Find(Sets.Crown_Zenith, 135, HoloRarity.SWSH_PIXEL_COSMOS_HOLO_LOST),
				HoloCards.Find(Sets.Scarlet_Violet, 181, HoloRarity.SV_PIXEL_COSMOS_HOLO),
				HoloCards.Find(Sets.Scarlet_Violet, 182, HoloRarity.SV_PIXEL_COSMOS_HOLO),
				HoloCards.Find(Sets.Scarlet_Violet, 191, HoloRarity.SV_PIXEL_COSMOS_HOLO),
				HoloCards.Find(Sets.Paldea_Evolved, 188, HoloRarity.SV_PIXEL_COSMOS_HOLO),
				HoloCards.Find(Sets.Paldea_Evolved, 189, HoloRarity.SV_PIXEL_COSMOS_HOLO),
				HoloCards.Find(Sets.Scarlet_Violet, 194, HoloRarity.SV_PIXEL_COSMOS_HOLO),
				HoloCards.Find(Sets.Crown_Zenith, 145, HoloRarity.SWSH_PIXEL_COSMOS_HOLO),
				HoloCards.Find(Sets.Crown_Zenith, 146, HoloRarity.SWSH_PIXEL_COSMOS_HOLO),
				HoloCards.Find(Sets.Scarlet_Violet, 196, HoloRarity.SV_PIXEL_COSMOS_HOLO),
				HoloCards.Find(Sets.Silver_Tempest, 167, HoloRarity.SWSH_PIXEL_COSMOS_HOLO),
				HoloCards.Find(Sets.Paldea_Evolved, 190, HoloRarity.SV_REVERSE_PIXEL_COSMOS_HOLO),
				HoloCards.Find(Sets.Paldea_Evolved, 191, HoloRarity.SV_REVERSE_PIXEL_COSMOS_HOLO),
				HoloCards.Find(Sets.Paldea_Evolved, 192, HoloRarity.SV_REVERSE_PIXEL_COSMOS_HOLO),
				HoloCards.FindUnnumbered("Basic Grass Energy", HoloRarity.SV_PIXEL_COSMOS_HOLO_ENERGY),
				HoloCards.FindUnnumbered("Basic Fire Energy", HoloRarity.SV_PIXEL_COSMOS_HOLO_ENERGY),
				HoloCards.FindUnnumbered("Basic Water Energy", HoloRarity.SV_PIXEL_COSMOS_HOLO_ENERGY),
				HoloCards.FindUnnumbered("Basic Lightning Energy", HoloRarity.SV_PIXEL_COSMOS_HOLO_ENERGY),
				HoloCards.FindUnnumbered("Basic Psychic Energy", HoloRarity.SV_PIXEL_COSMOS_HOLO_ENERGY),
				HoloCards.FindUnnumbered("Basic Fighting Energy", HoloRarity.SV_PIXEL_COSMOS_HOLO_ENERGY),
				HoloCards.FindUnnumbered("Basic Darkness Energy", HoloRarity.SV_PIXEL_COSMOS_HOLO_ENERGY),
				HoloCards.FindUnnumbered("Basic Metal Energy", HoloRarity.SV_PIXEL_COSMOS_HOLO_ENERGY)
			),
		};

		public static PrizePack[] Get()
		{
			return ThePrizePacks;
		}
	}
}