namespace TCG
{
	public enum Sets
	{
		Unknown,
		Unnumbered_Promo,
		Metal_Cards,
		
		Team_Rocket,
		
		Neo_Revelation,
		Neo_Destiny,
		Japanese_Neo,
		
		Aquapolis,
		Skyridge,
		
		EX_Ruby_Sapphire,
		EX_Sandstorm,
		EX_Dragon,
		EX_Team_Magma_vs_Team_Aqua,
		EX_Hidden_Legends,
		EX_FireRed_LeafGreen,
		EX_Team_Rocket_Returns,
		EX_Deoxys,
		EX_Emerald,
		EX_Unseen_Forces,
		EX_Delta_Species,
		EX_Legend_Maker,
		EX_Holon_Phantoms,
		EX_Crystal_Guardians,
		EX_Dragon_Frontiers,
		EX_Power_Keepers,
		POP_Series_1,
		POP_Series_2,
		POP_Series_3,
		POP_Series_4,
		POP_Series_5,
		EX_Promo,
		Japanese_EX,
		
		Diamond_Pearl,
		Mysterious_Treasures,
		Secret_Wonders,
		Great_Encounters,
		Majestic_Dawn,
		Legends_Awakened,
		Stormfront,
		Platinum,
		Rising_Rivals,
		Supreme_Victors,
		Arceus,
		DP_Promo,
		Japanese_DP,
		
		HeartGold_SoulSilver,
		Unleashed,
		Undaunted,
		Triumphant,
		Call_of_Legends,
		HGSS_Promo,
		Japanese_HGSS,
		
		Black_White,
		Emerging_Powers,
		Noble_Victories,
		Next_Destinies,
		Dark_Explorers,
		Dragons_Exalted,
		Dragon_Vault,
		Boundaries_Crossed,
		Plasma_Storm,
		Plasma_Freeze,
		Plasma_Blast,
		Legendary_Treasures,
		Legendary_Treasures_RC,
		BW_Promo,
		
		XY,
		Flashfire,
		Furious_Fists,
		Phantom_Forces,
		Primal_Clash,
		Double_Crisis,
		Roaring_Skies,
		Ancient_Origins,
		BREAKthrough,
		BREAKpoint,
		Generations,
		Generations_RC,
		Fates_Collide,
		Steam_Siege,
		Evolutions,
		XY_Promo,
		XY_Yellow_A_Promo,
		Japanese_BW_XY,
		
		Sun_Moon,
		Guardians_Rising,
		Burning_Shadows,
		Shining_Legends,
		Crimson_Invasion,
		Ultra_Prism,
		Forbidden_Light,
		Celestial_Storm,
		Dragon_Majesty,
		Lost_Thunder,
		Team_Up,
		Unbroken_Bonds,
		Unified_Minds,
		Hidden_Fates,
		Hidden_Fates_SV,
		Cosmic_Eclipse,
		SM_Promo,
		SM_Yellow_A_Promo,
		Japanese_SM,
		
		Sword_Shield,
		Rebel_Clash,
		Darkness_Ablaze,
		Champions_Path,
		Vivid_Voltage,
		Shining_Fates,
		Shining_Fates_SV,
		Battle_Styles,
		Chilling_Reign,
		Evolving_Skies,
		Celebrations,
		Fusion_Strike,
		Brilliant_Stars,
		Astral_Radiance,
		Pokémon_GO,
		Lost_Origin,
		Silver_Tempest,
		Crown_Zenith,
		Crown_Zenith_Galarian_Gallery,
		SWSH_Promo,
		Japanese_SWSH,
		
		Scarlet_Violet,
		Paldea_Evolved,
		SV_Promo,

		Length,
	}
}