using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TCG
{
	public static class WorldsCards
	{
		private static WorldsCard[] TheCards =
		{
			new WorldsCard("Swampert ex", Pokedex.Swampert, Rarity.ex, Types.Fighting, Sets.EX_Team_Magma_vs_Team_Aqua, 95, 2004),
			new WorldsCard("Suicune ex", Pokedex.Suicune, Rarity.ex, Types.Water, Sets.EX_Team_Magma_vs_Team_Aqua, 94, 2004),
			new WorldsCard("Gardevoir ex", Pokedex.Gardevoir, Rarity.ex, Types.Psychic, Sets.EX_Sandstorm, 96, 2004),
			new WorldsCard("Blaziken ex", Pokedex.Blaziken, Rarity.ex, Types.Fire, Sets.EX_Team_Magma_vs_Team_Aqua, 89, 2004),
			new WorldsCard("Rayquaza ex", Pokedex.Rayquaza, Rarity.ex, Types.Colorless, Sets.EX_Dragon, 97, 2004),
			new WorldsCard("Medicham ex", Pokedex.Medicham, Rarity.ex, Types.Fighting, Sets.EX_Emerald, 95, 2005),
			new WorldsCard("Mew ex", Pokedex.Mew, Rarity.ex, Types.Psychic, Sets.EX_Legend_Maker, 88, 2006),
			new WorldsCard("Manectric ex", Pokedex.Manectric, Rarity.ex, Types.Lightning, Sets.EX_Deoxys, 101, 2006),
			new WorldsCard("Regirock ex", Pokedex.Regirock, Rarity.ex, Types.Fighting, Sets.EX_Hidden_Legends, 98, 2006),
			new WorldsCard("Deoxys ex", Pokedex.Deoxys, Rarity.ex, Types.Psychic, Sets.EX_Emerald, 93, 2006),
			new WorldsCard("Lugia ex", Pokedex.Lugia, Rarity.ex, Types.Colorless, Sets.EX_Unseen_Forces, 105, 2006),
			new WorldsCard("Blastoise ex", Pokedex.Blastoise, Rarity.ex, Types.Water, Sets.EX_FireRed_LeafGreen, 104, 2006),
			new WorldsCard("Steelix ex", Pokedex.Steelix, Rarity.ex, Types.Metal, Sets.EX_Unseen_Forces, 109, 2006),
			new WorldsCard("Latias ?", Pokedex.Latias, Rarity.Gold_Star, Types.Colorless, Sets.EX_Deoxys, 105, 2006),
			new WorldsCard("Flareon ex", Pokedex.Flareon, Rarity.ex, Types.Fire, Sets.EX_Delta_Species, 108, 2006),
			new WorldsCard("Umbreon ex", Pokedex.Umbreon, Rarity.ex, Types.Darkness, Sets.EX_Unseen_Forces, 112, 2006),
			new WorldsCard("Espeon ex", Pokedex.Espeon, Rarity.ex, Types.Psychic, Sets.EX_Unseen_Forces, 102, 2006),
			new WorldsCard("Jolteon ex", Pokedex.Jolteon, Rarity.ex, Types.Lightning, Sets.EX_Delta_Species, 109, 2006),
			new WorldsCard("Vaporeon ex", Pokedex.Vaporeon, Rarity.ex, Types.Water, Sets.EX_Delta_Species, 110, 2006),
			new WorldsCard("Flygon ex δ", Pokedex.Flygon, Rarity.Delta_Species_ex, Types.Psychic, Sets.EX_Dragon_Frontiers, 92, 2007),
			new WorldsCard("Jolteon ex", Pokedex.Jolteon, Rarity.ex, Types.Lightning, Sets.EX_Delta_Species, 109, 2007),
			new WorldsCard("Vaporeon ex", Pokedex.Vaporeon, Rarity.ex, Types.Water, Sets.EX_Delta_Species, 110, 2007),
			new WorldsCard("Absol ex", Pokedex.Absol, Rarity.ex, Types.Darkness, Sets.EX_Power_Keepers, 92, 2007),
			new WorldsCard("Rayquaza ex δ", Pokedex.Rayquaza, Rarity.Delta_Species_ex, Types.Lightning, Sets.EX_Dragon_Frontiers, 97, 2007),
			new WorldsCard("Absol ex", Pokedex.Absol, Rarity.ex, Types.Darkness, Sets.EX_Power_Keepers, 92, 2007),
			new WorldsCard("Mew ex", Pokedex.Mew, Rarity.ex, Types.Psychic, Sets.EX_Legend_Maker, 88, 2007),
			new WorldsCard("Espeon ex", Pokedex.Espeon, Rarity.ex, Types.Psychic, Sets.EX_Unseen_Forces, 102, 2007),
			new WorldsCard("Jolteon ex", Pokedex.Jolteon, Rarity.ex, Types.Lightning, Sets.EX_Delta_Species, 109, 2007),
			new WorldsCard("Vaporeon ex", Pokedex.Vaporeon, Rarity.ex, Types.Water, Sets.EX_Delta_Species, 110, 2007),
			new WorldsCard("Jolteon ?", Pokedex.Jolteon, Rarity.Gold_Star, Types.Lightning, Sets.EX_Power_Keepers, 101, 2007),
			new WorldsCard("Jirachi ex", Pokedex.Jirachi, Rarity.ex, Types.Psychic, Sets.EX_Crystal_Guardians, 94, 2007),
			new WorldsCard("Banette ex", Pokedex.Banette, Rarity.ex, Types.Psychic, Sets.EX_Legend_Maker, 85, 2007),
			new WorldsCard("Mew ? δ", Pokedex.Mew, Rarity.Delta_Species_Gold_Star, Types.Water, Sets.EX_Dragon_Frontiers, 101, 2008),
			new WorldsCard("Gardevoir LV.X", Pokedex.Gardevoir, Rarity.LV_X, Types.Psychic, Sets.Secret_Wonders, 131, 2008),
			new WorldsCard("Jolteon ?", Pokedex.Jolteon, Rarity.Gold_Star, Types.Lightning, Sets.EX_Power_Keepers, 101, 2008),
			new WorldsCard("Jirachi ex", Pokedex.Jirachi, Rarity.ex, Types.Psychic, Sets.EX_Crystal_Guardians, 94, 2008),
			new WorldsCard("Flygon LV.X", Pokedex.Flygon, Rarity.LV_X, Types.Colorless, Sets.Rising_Rivals, 105, 2009),
			new WorldsCard("Mewtwo LV.X", Pokedex.Mewtwo, Rarity.LV_X, Types.Psychic, Sets.Legends_Awakened, 144, 2009),
			new WorldsCard("Palkia LV.X", Pokedex.Palkia, Rarity.LV_X, Types.Water, Sets.DP_Promo, 18, 2009),
			new WorldsCard("Luxray GL LV.X", Pokedex.Luxray, Rarity.LV_X_SP, Types.Lightning, Sets.Rising_Rivals, 109, 2009),
			new WorldsCard("Uxie LV.X", Pokedex.Uxie, Rarity.LV_X, Types.Psychic, Sets.Legends_Awakened, 146, 2009),
			new WorldsCard("Dialga G LV.X", Pokedex.Dialga, Rarity.LV_X_SP, Types.Metal, Sets.Platinum, 122, 2009),
			new WorldsCard("Luxray GL LV.X", Pokedex.Luxray, Rarity.LV_X_SP, Types.Lightning, Sets.Rising_Rivals, 109, 2009),
			new WorldsCard("Garchomp C LV.X", Pokedex.Garchomp, Rarity.LV_X_SP, Types.Colorless, Sets.Supreme_Victors, 145, 2010),
			new WorldsCard("Luxray GL LV.X", Pokedex.Luxray, Rarity.LV_X_SP, Types.Lightning, Sets.Rising_Rivals, 109, 2010),
			new WorldsCard("Dialga G LV.X", Pokedex.Dialga, Rarity.LV_X_SP, Types.Metal, Sets.Platinum, 122, 2010),
			new WorldsCard("Uxie LV.X", Pokedex.Uxie, Rarity.LV_X, Types.Psychic, Sets.Legends_Awakened, 146, 2010),
			new WorldsCard("Luxray GL LV.X", Pokedex.Luxray, Rarity.LV_X_SP, Types.Lightning, Sets.Rising_Rivals, 109, 2010),
			new WorldsCard("Gardevoir LV.X", Pokedex.Gardevoir, Rarity.LV_X, Types.Psychic, Sets.Secret_Wonders, 131, 2010),
			new WorldsCard("Azelf LV.X", Pokedex.Azelf, Rarity.LV_X, Types.Psychic, Sets.Legends_Awakened, 140, 2010),
			new WorldsCard("Magnezone", Pokedex.Magnezone, Rarity.Prime, Types.Lightning, Sets.Triumphant, 96, 2011),
			new WorldsCard("Yanmega", Pokedex.Yanmega, Rarity.Prime, Types.Grass, Sets.Triumphant, 98, 2011),
			new WorldsCard("Kingdra", Pokedex.Kingdra, Rarity.Prime, Types.Water, Sets.Unleashed, 85, 2011),
			new WorldsCard("Typhlosion", Pokedex.Typhlosion, Rarity.Prime, Types.Fire, Sets.HeartGold_SoulSilver, 110, 2011),
			new WorldsCard("Donphan", Pokedex.Donphan, Rarity.Prime, Types.Fighting, Sets.HeartGold_SoulSilver, 107, 2011),
			new WorldsCard("Blissey", Pokedex.Blissey, Rarity.Prime, Types.Colorless, Sets.HeartGold_SoulSilver, 106, 2011),
			new WorldsCard("Suicune & Entei LEGEND", Pokedex.Suicune, Rarity.LEGEND, Types.Other, Sets.Unleashed, 94, 2011),
			new WorldsCard("Suicune & Entei LEGEND", Pokedex.Suicune, Rarity.LEGEND, Types.Other, Sets.Unleashed, 95, 2011),
			new WorldsCard("Magnezone", Pokedex.Magnezone, Rarity.Prime, Types.Lightning, Sets.Triumphant, 96, 2011),
			new WorldsCard("Rayquaza & Deoxys LEGEND", Pokedex.Rayquaza, Rarity.LEGEND, Types.Other, Sets.Undaunted, 89, 2011),
			new WorldsCard("Rayquaza & Deoxys LEGEND", Pokedex.Rayquaza, Rarity.LEGEND, Types.Other, Sets.Undaunted, 90, 2011),
			new WorldsCard("Darkrai EX", Pokedex.Darkrai, Rarity.EX, Types.Darkness, Sets.Dark_Explorers, 63, 2012),
			new WorldsCard("Mewtwo EX", Pokedex.Mewtwo, Rarity.EX, Types.Psychic, Sets.Next_Destinies, 54, 2012),
			new WorldsCard("Mewtwo EX", Pokedex.Mewtwo, Rarity.EX, Types.Psychic, Sets.Next_Destinies, 54, 2012),
			new WorldsCard("Mewtwo EX", Pokedex.Mewtwo, Rarity.EX, Types.Psychic, Sets.Next_Destinies, 54, 2012),
			new WorldsCard("Raikou EX", Pokedex.Raikou, Rarity.EX, Types.Lightning, Sets.Dark_Explorers, 38, 2012),
			new WorldsCard("Celebi", Pokedex.Celebi, Rarity.Prime, Types.Grass, Sets.Triumphant, 92, 2012),
			new WorldsCard("Tornadus EX", Pokedex.Tornadus, Rarity.EX, Types.Colorless, Sets.Dark_Explorers, 90, 2012),
			new WorldsCard("Mewtwo EX", Pokedex.Mewtwo, Rarity.EX, Types.Psychic, Sets.Next_Destinies, 54, 2012),
			new WorldsCard("Mew EX", Pokedex.Mew, Rarity.EX, Types.Psychic, Sets.Dragons_Exalted, 46, 2013),
			new WorldsCard("Keldeo EX", Pokedex.Keldeo, Rarity.EX, Types.Water, Sets.Boundaries_Crossed, 49, 2013),
			new WorldsCard("Computer Search", Pokedex.NVT, Rarity.Ace_Spec, Types.Item, Sets.Boundaries_Crossed, 137, 2013),
			new WorldsCard("Darkrai EX", Pokedex.Darkrai, Rarity.EX, Types.Darkness, Sets.Dark_Explorers, 63, 2013),
			new WorldsCard("Keldeo EX", Pokedex.Keldeo, Rarity.EX, Types.Water, Sets.Boundaries_Crossed, 49, 2013),
			new WorldsCard("Computer Search", Pokedex.NVT, Rarity.Ace_Spec, Types.Item, Sets.Boundaries_Crossed, 137, 2013),
			new WorldsCard("Rayquaza EX", Pokedex.Rayquaza, Rarity.EX, Types.Dragon, Sets.Dragons_Exalted, 85, 2013),
			new WorldsCard("Raikou EX", Pokedex.Raikou, Rarity.EX, Types.Lightning, Sets.Dark_Explorers, 38, 2013),
			new WorldsCard("Keldeo EX", Pokedex.Keldeo, Rarity.EX, Types.Water, Sets.Boundaries_Crossed, 49, 2013),
			new WorldsCard("Dowsing Machine", Pokedex.NVT, Rarity.Ace_Spec, Types.Item, Sets.Plasma_Storm, 128, 2013),
			new WorldsCard("Thundurus EX", Pokedex.Thundurus, Rarity.EX_Plasma, Types.Lightning, Sets.Plasma_Freeze, 38, 2013),
			new WorldsCard("Deoxys EX", Pokedex.Deoxys, Rarity.EX_Plasma, Types.Psychic, Sets.Plasma_Freeze, 53, 2013),
			new WorldsCard("Computer Search", Pokedex.NVT, Rarity.Ace_Spec, Types.Item, Sets.Boundaries_Crossed, 137, 2013),
			new WorldsCard("Deoxys EX", Pokedex.Deoxys, Rarity.EX_Plasma, Types.Psychic, Sets.Plasma_Freeze, 53, 2014),
			new WorldsCard("Latias EX", Pokedex.Latias, Rarity.EX, Types.Dragon, Sets.Plasma_Freeze, 85, 2014),
			new WorldsCard("Thundurus EX", Pokedex.Thundurus, Rarity.EX_Plasma, Types.Lightning, Sets.Plasma_Freeze, 38, 2014),
			new WorldsCard("Scramble Switch", Pokedex.NVT, Rarity.Ace_Spec, Types.Item, Sets.Plasma_Storm, 129, 2014),
			new WorldsCard("Mew EX", Pokedex.Mew, Rarity.EX, Types.Psychic, Sets.Dragons_Exalted, 46, 2014),
			new WorldsCard("Computer Search", Pokedex.NVT, Rarity.Ace_Spec, Types.Item, Sets.Boundaries_Crossed, 137, 2014),
			new WorldsCard("Genesect EX", Pokedex.Genesect, Rarity.EX_Plasma, Types.Grass, Sets.Plasma_Blast, 11, 2014),
			new WorldsCard("Jirachi EX", Pokedex.Jirachi, Rarity.EX, Types.Metal, Sets.Plasma_Blast, 60, 2014),
			new WorldsCard("Virizion EX", Pokedex.Virizion, Rarity.EX, Types.Grass, Sets.Plasma_Blast, 9, 2014),
			new WorldsCard("G Booster", Pokedex.NVT, Rarity.Ace_Spec_Plasma, Types.Tool, Sets.Plasma_Blast, 92, 2014),
			new WorldsCard("M Kangaskhan EX", Pokedex.Kangaskhan, Rarity.M_EX, Types.Colorless, Sets.Flashfire, 79, 2014),
			new WorldsCard("Kangaskhan EX", Pokedex.Kangaskhan, Rarity.EX, Types.Colorless, Sets.Flashfire, 78, 2014),
			new WorldsCard("Keldeo EX", Pokedex.Keldeo, Rarity.EX, Types.Water, Sets.Legendary_Treasures, 45, 2014),
			new WorldsCard("Mewtwo EX", Pokedex.Mewtwo, Rarity.EX, Types.Psychic, Sets.Legendary_Treasures, 54, 2014),
			new WorldsCard("Xerneas EX", Pokedex.Xerneas, Rarity.EX, Types.Fairy, Sets.XY, 97, 2014),
			new WorldsCard("Dowsing Machine", Pokedex.NVT, Rarity.Ace_Spec, Types.Item, Sets.Plasma_Storm, 128, 2014),
			new WorldsCard("Primal Groudon EX", Pokedex.Groudon, Rarity.M_EX_Primal, Types.Fighting, Sets.Primal_Clash, 86, 2015),
			new WorldsCard("Groudon EX", Pokedex.Groudon, Rarity.EX, Types.Fighting, Sets.Primal_Clash, 85, 2015),
			new WorldsCard("Bunnelby", Pokedex.Bunnelby, Rarity.Ancient_Trait_Omega, Types.Colorless, Sets.Primal_Clash, 121, 2015),
			new WorldsCard("Landorus EX", Pokedex.Landorus, Rarity.EX, Types.Fighting, Sets.Boundaries_Crossed, 89, 2015),
			new WorldsCard("Shaymin EX", Pokedex.Shaymin, Rarity.EX, Types.Colorless, Sets.Roaring_Skies, 77, 2015),
			new WorldsCard("Lucario EX", Pokedex.Lucario, Rarity.EX, Types.Fighting, Sets.Furious_Fists, 54, 2015),
			new WorldsCard("Scoop Up Cyclone", Pokedex.NVT, Rarity.Ace_Spec, Types.Item, Sets.Plasma_Blast, 95, 2015),
			new WorldsCard("Seismitoad EX", Pokedex.Seismitoad, Rarity.EX, Types.Water, Sets.Furious_Fists, 20, 2015),
			new WorldsCard("Shaymin EX", Pokedex.Shaymin, Rarity.EX, Types.Colorless, Sets.Roaring_Skies, 77, 2015),
			new WorldsCard("Rock Guard", Pokedex.NVT, Rarity.Ace_Spec, Types.Tool, Sets.Plasma_Freeze, 108, 2015),
			new WorldsCard("Keldeo EX", Pokedex.Keldeo, Rarity.EX, Types.Water, Sets.Boundaries_Crossed, 49, 2015),
			new WorldsCard("Jirachi EX", Pokedex.Jirachi, Rarity.EX, Types.Metal, Sets.Plasma_Blast, 60, 2015),
			new WorldsCard("Shaymin EX", Pokedex.Shaymin, Rarity.EX, Types.Colorless, Sets.Roaring_Skies, 77, 2015),
			new WorldsCard("Articuno", Pokedex.Articuno, Rarity.Ancient_Trait_Delta, Types.Water, Sets.Roaring_Skies, 17, 2015),
			new WorldsCard("Mewtwo EX", Pokedex.Mewtwo, Rarity.EX, Types.Psychic, Sets.Legendary_Treasures, 54, 2015),
			new WorldsCard("Wailord EX", Pokedex.Wailord, Rarity.EX, Types.Water, Sets.Primal_Clash, 38, 2015),
			new WorldsCard("Computer Search", Pokedex.NVT, Rarity.Ace_Spec, Types.Item, Sets.Boundaries_Crossed, 137, 2015),
			new WorldsCard("Yanmega BREAK", Pokedex.Yanmega, Rarity.BREAK, Types.Grass, Sets.Steam_Siege, 8, 2016),
			new WorldsCard("Shaymin EX", Pokedex.Shaymin, Rarity.EX, Types.Colorless, Sets.Roaring_Skies, 77, 2016),
			new WorldsCard("M Audino EX", Pokedex.Audino, Rarity.M_EX, Types.Colorless, Sets.Fates_Collide, 85, 2016),
			new WorldsCard("Audino EX", Pokedex.Audino, Rarity.EX, Types.Colorless, Sets.Fates_Collide, 84, 2016),
			new WorldsCard("Shaymin EX", Pokedex.Shaymin, Rarity.EX, Types.Colorless, Sets.Roaring_Skies, 77, 2016),
			new WorldsCard("Hoopa EX", Pokedex.Hoopa, Rarity.EX, Types.Psychic, Sets.Ancient_Origins, 36, 2016),
			new WorldsCard("Magearna EX", Pokedex.Magearna, Rarity.EX, Types.Metal, Sets.Steam_Siege, 75, 2016),
			new WorldsCard("Parallel City", Pokedex.NVT, Rarity.Mirrored_Stadium, Types.Stadium, Sets.BREAKthrough, 145, 2016),
			new WorldsCard("Darkrai EX", Pokedex.Darkrai, Rarity.EX_Full_Art, Types.Darkness, Sets.BREAKpoint, 118, 2016),
			new WorldsCard("Giratina EX", Pokedex.Giratina, Rarity.EX, Types.Dragon, Sets.Ancient_Origins, 57, 2016),
			new WorldsCard("Shaymin EX", Pokedex.Shaymin, Rarity.EX, Types.Colorless, Sets.Roaring_Skies, 77, 2016),
			new WorldsCard("Hoopa EX", Pokedex.Hoopa, Rarity.EX, Types.Psychic, Sets.Ancient_Origins, 36, 2016),
			new WorldsCard("Greninja BREAK", Pokedex.Greninja, Rarity.BREAK, Types.Water, Sets.BREAKpoint, 41, 2016),
			new WorldsCard("Parallel City", Pokedex.NVT, Rarity.Mirrored_Stadium, Types.Stadium, Sets.BREAKthrough, 145, 2016),
			new WorldsCard("Reverse Valley", Pokedex.NVT, Rarity.Mirrored_Stadium, Types.Stadium, Sets.BREAKpoint, 110, 2016),
			new WorldsCard("Alolan Ninetales GX", Pokedex.Alolan_Ninetales, Rarity.GX, Types.Water, Sets.Guardians_Rising, 22, 2017),
			new WorldsCard("Tapu Lele GX", Pokedex.Tapu_Lele, Rarity.GX, Types.Psychic, Sets.Guardians_Rising, 60, 2017),
			new WorldsCard("Gardevoir GX", Pokedex.Gardevoir, Rarity.GX, Types.Fairy, Sets.Burning_Shadows, 93, 2017),
			new WorldsCard("Tapu Lele GX", Pokedex.Tapu_Lele, Rarity.GX, Types.Psychic, Sets.Guardians_Rising, 60, 2017),
			new WorldsCard("Golisopod GX", Pokedex.Golisopod, Rarity.GX, Types.Grass, Sets.Burning_Shadows, 17, 2017),
			new WorldsCard("Tapu Lele GX", Pokedex.Tapu_Lele, Rarity.GX, Types.Psychic, Sets.Guardians_Rising, 60, 2017),
			new WorldsCard("Decidueye GX", Pokedex.Decidueye, Rarity.GX, Types.Grass, Sets.Sun_Moon, 12, 2017),
			new WorldsCard("Golisopod GX", Pokedex.Golisopod, Rarity.GX, Types.Grass, Sets.Burning_Shadows, 17, 2017),
			new WorldsCard("Tapu Lele GX", Pokedex.Tapu_Lele, Rarity.GX, Types.Psychic, Sets.Guardians_Rising, 60, 2017),
			new WorldsCard("Espeon EX", Pokedex.Espeon, Rarity.EX, Types.Psychic, Sets.BREAKpoint, 52, 2017),
			new WorldsCard("Zoroark GX", Pokedex.Zoroark, Rarity.GX, Types.Darkness, Sets.Shining_Legends, 53, 2018),
			new WorldsCard("Tapu Lele GX", Pokedex.Tapu_Lele, Rarity.GX, Types.Psychic, Sets.Guardians_Rising, 60, 2018),
			new WorldsCard("Kartana GX", Pokedex.Kartana, Rarity.UB_GX, Types.Metal, Sets.Crimson_Invasion, 70, 2018),
			new WorldsCard("Parallel City", Pokedex.NVT, Rarity.Mirrored_Stadium, Types.Stadium, Sets.BREAKthrough, 145, 2018),
			new WorldsCard("Rayquaza GX", Pokedex.Rayquaza, Rarity.GX, Types.Dragon, Sets.Celestial_Storm, 109, 2018),
			new WorldsCard("Tapu Lele GX", Pokedex.Tapu_Lele, Rarity.GX, Types.Psychic, Sets.Guardians_Rising, 60, 2018),
			new WorldsCard("Xurkitree GX", Pokedex.Xurkitree, Rarity.UB_GX, Types.Lightning, Sets.SM_Promo, 68, 2018),
			new WorldsCard("Banette GX", Pokedex.Banette, Rarity.GX, Types.Psychic, Sets.Celestial_Storm, 66, 2018),
			new WorldsCard("Tapu Lele GX", Pokedex.Tapu_Lele, Rarity.GX, Types.Psychic, Sets.Guardians_Rising, 60, 2018),
			new WorldsCard("Drampa GX", Pokedex.Drampa, Rarity.GX, Types.Colorless, Sets.Guardians_Rising, 115, 2018),
			new WorldsCard("Parallel City", Pokedex.NVT, Rarity.Mirrored_Stadium, Types.Stadium, Sets.BREAKthrough, 145, 2018),
			new WorldsCard("Buzzwole GX", Pokedex.Buzzwole, Rarity.UB_GX, Types.Fighting, Sets.Crimson_Invasion, 57, 2018),
			new WorldsCard("Lycanroc GX", Pokedex.Lycanroc, Rarity.GX, Types.Fighting, Sets.Guardians_Rising, 74, 2018),
			new WorldsCard("Diancie Prism Star", Pokedex.Diancie, Rarity.Prism_Star, Types.Fighting, Sets.Forbidden_Light, 74, 2018),
			new WorldsCard("Beast Energy Prism Star", Pokedex.NVT, Rarity.Prism_Star, Types.Special_Energy, Sets.Forbidden_Light, 117, 2018),
			new WorldsCard("Blacephalon GX", Pokedex.Blacephalon, Rarity.UB_GX, Types.Fire, Sets.Lost_Thunder, 52, 2019),
			new WorldsCard("Naganadel GX", Pokedex.Naganadel, Rarity.UB_GX, Types.Dragon, Sets.Unified_Minds, 160, 2019),
			new WorldsCard("Heatran GX", Pokedex.Heatran, Rarity.GX, Types.Fire, Sets.Unified_Minds, 25, 2019),
			new WorldsCard("Dedenne GX", Pokedex.Dedenne, Rarity.GX, Types.Lightning, Sets.Unbroken_Bonds, 57, 2019),
			new WorldsCard("Heat Factory Prism Star", Pokedex.NVT, Rarity.Prism_Star, Types.Stadium, Sets.Lost_Thunder, 178, 2019),
			new WorldsCard("Beast Energy Prism Star", Pokedex.NVT, Rarity.Prism_Star, Types.Special_Energy, Sets.Forbidden_Light, 117, 2019),
			new WorldsCard("Pikachu & Zekrom GX", Pokedex.Pikachu, Rarity.TT_GX, Types.Lightning, Sets.Team_Up, 33, 2019),
			new WorldsCard("Raichu & Alolan Raichu GX", Pokedex.Raichu, Rarity.TT_GX, Types.Lightning, Sets.Unified_Minds, 54, 2019),
			new WorldsCard("Dedenne GX", Pokedex.Dedenne, Rarity.GX, Types.Lightning, Sets.Unbroken_Bonds, 57, 2019),
			new WorldsCard("Zeraora GX", Pokedex.Zeraora, Rarity.GX, Types.Lightning, Sets.Lost_Thunder, 86, 2019),
			new WorldsCard("Tapu Koko Prism Star", Pokedex.Tapu_Koko, Rarity.Prism_Star, Types.Lightning, Sets.Team_Up, 51, 2019),
			new WorldsCard("Thunder Mountain Prism Star", Pokedex.NVT, Rarity.Prism_Star, Types.Stadium, Sets.Lost_Thunder, 191, 2019),
			new WorldsCard("Mewtwo & Mew GX", Pokedex.Mewtwo, Rarity.TT_GX, Types.Psychic, Sets.Unified_Minds, 71, 2019),
			new WorldsCard("Dedenne GX", Pokedex.Dedenne, Rarity.GX, Types.Lightning, Sets.Unbroken_Bonds, 57, 2019),
			new WorldsCard("Cobalion GX", Pokedex.Cobalion, Rarity.GX, Types.Metal, Sets.Team_Up, 106, 2019),
			new WorldsCard("Espeon & Deoxys GX", Pokedex.Espeon, Rarity.TT_GX, Types.Psychic, Sets.Unified_Minds, 72, 2019),
			new WorldsCard("Jirachi GX", Pokedex.Jirachi, Rarity.GX, Types.Psychic, Sets.Unified_Minds, 79, 2019),
			new WorldsCard("Latios GX", Pokedex.Latios, Rarity.GX, Types.Psychic, Sets.Unified_Minds, 78, 2019),
			new WorldsCard("Magcargo GX", Pokedex.Magcargo, Rarity.GX, Types.Fire, Sets.Lost_Thunder, 44, 2019),
			new WorldsCard("Naganadel GX", Pokedex.Naganadel, Rarity.UB_GX, Types.Dragon, Sets.Unified_Minds, 160, 2019),
			new WorldsCard("Reshiram & Charizard GX", Pokedex.Reshiram, Rarity.TT_GX, Types.Fire, Sets.Unbroken_Bonds, 20, 2019),
			new WorldsCard("Solgaleo GX", Pokedex.Solgaleo, Rarity.GX, Types.Metal, Sets.SM_Promo, 16, 2019),
			new WorldsCard("Reshiram & Charizard GX", Pokedex.Reshiram, Rarity.TT_GX, Types.Fire, Sets.Unbroken_Bonds, 20, 2019),
			new WorldsCard("Dedenne GX", Pokedex.Dedenne, Rarity.GX, Types.Lightning, Sets.Unbroken_Bonds, 57, 2019),
			new WorldsCard("Heatran GX", Pokedex.Heatran, Rarity.GX, Types.Fire, Sets.Unified_Minds, 25, 2019),
			new WorldsCard("Victini Prism Star", Pokedex.Victini, Rarity.Prism_Star, Types.Fire, Sets.Dragon_Majesty, 7, 2019),
			new WorldsCard("Heat Factory Prism Star", Pokedex.NVT, Rarity.Prism_Star, Types.Stadium, Sets.Lost_Thunder, 178, 2019),
			new WorldsCard("Origin Forme Palkia VSTAR", Pokedex.Palkia, Rarity.VSTAR, Types.Water, Sets.Astral_Radiance, 40, 2022),
			new WorldsCard("Origin Forme Palkia V", Pokedex.Palkia, Rarity.V, Types.Water, Sets.Astral_Radiance, 39, 2022),
			new WorldsCard("Ice Rider Calyrex VMAX", Pokedex.Ice_Rider_Calyrex, Rarity.VMAX_Blue, Types.Water, Sets.Chilling_Reign, 46, 2022),
			new WorldsCard("Ice Rider Calyrex V", Pokedex.Ice_Rider_Calyrex, Rarity.V, Types.Water, Sets.Chilling_Reign, 45, 2022),
			new WorldsCard("Rapid Strike Urshifu VMAX", Pokedex.Rapid_Strike_Urshifu, Rarity.VMAX_Gigantamax, Types.Fighting, Sets.Battle_Styles, 88, 2022),
			new WorldsCard("Rapid Strike Urshifu V", Pokedex.Rapid_Strike_Urshifu, Rarity.V, Types.Fighting, Sets.Battle_Styles, 87, 2022),
			new WorldsCard("Medicham V", Pokedex.Medicham, Rarity.V, Types.Fighting, Sets.Evolving_Skies, 83, 2022),
			new WorldsCard("Mew VMAX", Pokedex.Mew, Rarity.VMAX, Types.Psychic, Sets.Fusion_Strike, 114, 2022),
			new WorldsCard("Mew V", Pokedex.Mew, Rarity.V, Types.Psychic, Sets.Fusion_Strike, 113, 2022),
			new WorldsCard("Genesect V", Pokedex.Genesect, Rarity.V, Types.Metal, Sets.Fusion_Strike, 185, 2022),
			new WorldsCard("Arceus VSTAR", Pokedex.Arceus, Rarity.VSTAR, Types.Colorless, Sets.Brilliant_Stars, 123, 2022),
			new WorldsCard("Arceus V", Pokedex.Arceus, Rarity.V, Types.Colorless, Sets.Brilliant_Stars, 122, 2022),
			new WorldsCard("Flying Pikachu VMAX", Pokedex.Flying_Pikachu, Rarity.VMAX, Types.Lightning, Sets.Celebrations, 7, 2022),
			new WorldsCard("Flying Pikachu V", Pokedex.Flying_Pikachu, Rarity.V, Types.Lightning, Sets.Celebrations, 6, 2022),
			new WorldsCard("Hisuian Decidueye VSTAR", Pokedex.Hisuian_Decidueye, Rarity.VSTAR, Types.Fighting, Sets.Astral_Radiance, 84, 2022),
			new WorldsCard("Hisuian Decidueye V", Pokedex.Hisuian_Decidueye, Rarity.V, Types.Fighting, Sets.Astral_Radiance, 83, 2022),
			new WorldsCard("Lumineon V", Pokedex.Lumineon, Rarity.V, Types.Water, Sets.Brilliant_Stars, 40, 2022),
			new WorldsCard("Crobat V", Pokedex.Crobat, Rarity.V, Types.Darkness, Sets.Darkness_Ablaze, 104, 2022),
			// new WorldsCard("Swampert ex", Pokedex.Swampert, Rarity.ex, Types.Fighting, Sets.EX_Team_Magma_vs_Team_Aqua, 95, 2007),
			// new WorldsCard("Swampert ex", Pokedex.Swampert, Rarity.ex, Types.Fighting, Sets.EX_Team_Magma_vs_Team_Aqua, 95, 2007),
			// new WorldsCard("Swampert ex", Pokedex.Swampert, Rarity.ex, Types.Fighting, Sets.EX_Team_Magma_vs_Team_Aqua, 95, 2007),
			// new WorldsCard("Swampert ex", Pokedex.Swampert, Rarity.ex, Types.Fighting, Sets.EX_Team_Magma_vs_Team_Aqua, 95, 2007),
			// new WorldsCard("Swampert ex", Pokedex.Swampert, Rarity.ex, Types.Fighting, Sets.EX_Team_Magma_vs_Team_Aqua, 95, 2007),
			// new WorldsCard("Swampert ex", Pokedex.Swampert, Rarity.ex, Types.Fighting, Sets.EX_Team_Magma_vs_Team_Aqua, 95, 2007),
			// new WorldsCard("Swampert ex", Pokedex.Swampert, Rarity.ex, Types.Fighting, Sets.EX_Team_Magma_vs_Team_Aqua, 95, 2007),
			// new WorldsCard("Swampert ex", Pokedex.Swampert, Rarity.ex, Types.Fighting, Sets.EX_Team_Magma_vs_Team_Aqua, 95, 2007),
			// new WorldsCard("Swampert ex", Pokedex.Swampert, Rarity.ex, Types.Fighting, Sets.EX_Team_Magma_vs_Team_Aqua, 95, 2007),
			// new WorldsCard("Swampert ex", Pokedex.Swampert, Rarity.ex, Types.Fighting, Sets.EX_Team_Magma_vs_Team_Aqua, 95, 2007),
		};
		
		public static WorldsCard[] Get(bool removeStamped = true)
		{
			return TheCards;
		}

		public static WorldsCard Find(Sets set, double setNum)
		{
			return TheCards.Where(c => c.set == set && c.setNum == setNum).First();
		}
		
		public static WorldsCard[] HasDuplicates()
		{
			int count = TheCards.Length;
			
			for (int i = 0; i < count; i++)
			{
				for (int j = 0; j < count; j++)
				{
					if (i != j && TheCards[i].IsEqualTo(TheCards[j]))
						return new WorldsCard[] { TheCards[i], TheCards[j] };
				}
			}
			
			return null;
		}
	}
}